### ISSUE TITLE
[Crash]: AnimFix

### ISSUE THREAD

**Issue by Khikki** [FalsePattern/AnimFix#3]
### OS

Windows

### GPU

Intel

### Game log

---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/17/22 1:00 PM
Description: Registering texture

java.lang.IllegalStateException: Failed to extract animated texture stitching slot!
	at net.minecraft.client.renderer.texture.Stitcher.handler$doStitch_1$zzo000(Stitcher.java:608)
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:85)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:357)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:152)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:215)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:2987)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:136)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at pro.gravit.launcher.kHIkKIAClgW4DP.kHIKKI4qpHwUU2(Unknown Source)
	at pro.gravit.launcher.kHIkKIAClgW4DP.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.Stitcher.handler$doStitch_1$zzo000(Stitcher.java:608)
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:85)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:357)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:152)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/atlas/items.png
	Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:215)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:2987)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:136)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at pro.gravit.launcher.kHIkKIAClgW4DP.kHIKKI4qpHwUU2(Unknown Source)
	at pro.gravit.launcher.kHIkKIAClgW4DP.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_321, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 423798832 bytes (404 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 6 total; -XX:+DisableAttachMechanism -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 108 mods loaded, 108 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UCHIJA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJA	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJA	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJA	xaeroworldmap_core{1.7.10-1.0} [XaeroWorldMapCore] (minecraft.jar) 
	UCHIJA	falsepatternlib{0.3.2} [FalsePatternLib] (minecraft.jar) 
	UCHIJA	ClientFixer{1.0} [ClientFixer] (minecraft.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5-client.jar) 
	UCHIJA	Botania{r1.8-249} [Botania] (Botania-r1.8-249.jar) 
	UCHIJA	AdvancedBotany{1.2.3.2} [Advanced Botany] (Advanced+Botany+1.2.3.2.jar) 
	UCHIJA	spongemixins{1.4.0} [SpongeMixins Loader] (SpongeMixins-1.4.0.jar) 
	UCHIJA	animfix{1.3.3} [AnimFix] (animfix-mc1.7.10-1.3.3.jar) 
	UCHIJA	armorchroma{1.2} [Armor Chroma] (armorchroma-1.2-1.7.10.jar) 
	UCHIJA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJA	ArmorStatusHUD{1.28} [ArmorStatusHUD] (ArmorStatusHUD-client-1.28.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
	UCHIJA	betterquesting{3.0.328} [Better Questing] (BetterQuesting-3.0.328.jar) 
	UCHIJA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft-1.11.7.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.1a2.jar) 
	UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCHIJA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-538.jar) 
	UCHIJA	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (ForbiddenMagic.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJA	BloodArsenal{1.2-5} [Blood Arsenal] (BloodArsenal-1.7.10-1.2-5.jar) 
	UCHIJA	VillageNames{4.3.11} [§6Village Names] (VillageNames-1.7.10-4.3.11.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJA	bugtorch{1.1.6} [BugTorch] (bugtorch-1.7.10-1.1.6.jar) 
	UCHIJA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenters-Blocks-3.3.8.1.jar) 
	UCHIJA	coretweaks{0.2.2} [CoreTweaks] (CoreTweaks-1.7.10-0.2.2.jar) 
	UCHIJA	customguiscreens{1.3} [Custom GUI Screens] (customguiscreens-1.3.jar) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damageindicatorsmod-3_2_0.jar) 
	UCHIJA	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCHIJA	emojicord{1.1.1.39} [Emojicord] (Emojicord-1.7.10-1.1.1.39-universal.jar) 
	UCHIJA	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion-1.8.6.jar) 
	UCHIJA	etfuturum{2.3.2} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.3.2.jar) 
	UCHIJA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's+HarvestCraft+1.7.10Lb.jar) 
	UCHIJA	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
	UCHIJA	fairylights{1.4.0} [Fairy Lights] (Fairylights-1.4.0-1.7.10.jar) 
	UCHIJA	floatingitems{0.1.0} [FloatingItems] (FloatingItems-1.7.10-0.1.0.jar) 
	UCHIJA	flyingcullers{1.3} [§cF§6l§ey§ai§bn§9g §fCu§7lle§8rs§r] (FlyingCullers-1.7.10-1.3.jar) 
	UCHIJA	gadomancy{1.0.7.3} [Gadomancy] (gadomancy-1.7.10-1.0.7.3.jar) 
	UCHIJA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
	UCHIJA	Growthcraft{1.7.10-2.7.2} [Growthcraft] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJA	Growthcraft|Cellar{1.7.10-2.7.2} [Growthcraft Cellar] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJA	Growthcraft|Apples{1.7.10-2.7.2} [Growthcraft Apples] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJA	Growthcraft|Bamboo{1.7.10-2.7.2} [Growthcraft Bamboo] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJA	Growthcraft|Bees{1.7.10-2.7.2} [Growthcraft Bees] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJA	Growthcraft|Fishtrap{1.7.10-2.7.2} [Growthcraft Fishtrap] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJA	Growthcraft|Grapes{1.7.10-2.7.2} [Growthcraft Grapes] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJA	Growthcraft|Hops{1.7.10-2.7.2} [Growthcraft Hops] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJA	Growthcraft|Milk{1.7.10-2.7.2} [Growthcraft Milk] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJA	Growthcraft|Rice{1.7.10-2.7.2} [Growthcraft Rice] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJA	ImLookingAtBlood{1.1} [I'm Looking At Blood] (ImLookingAtBlood-1.7.2-1.1a.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJA	Magistics{BR4-181-g74f4309} [Magistics] (Magistics-BR4-181-g74f4309.jar) 
	UCHIJA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJA	mixingasm{0.2.1} [Mixingasm] (mixingasm-1.7.10-0.2.1.jar) 
	UCHIJA	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCHIJA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	netherlicious{3.1.0} [§6Netherlicious] (netherlicious-3.1.0.jar) 
	UCHIJA	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) 
	UCHIJA	Personalize{1.0} [Personalize] (Personalization.jar) 
	UCHIJA	questbook{3.0.0-1.7.10} [Better Questing Quest Book] (questbook-3.0.0-1.7.10.jar) 
	UCHIJA	RGHelper{0.2} [RGHelper] (rghelper-1.1.jar) 
	UCHIJA	StatusEffectHUD{1.27} [StatusEffectHUD] (StatusEffectHUD-client-1.27.jar) 
	UCHIJA	TaintedMagic{r7.82} [Tainted Magic] (TaintedMagic-r7.82.jar) 
	UCHIJA	tcinventoryscan{1.0.11} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.11.jar) 
	UCHIJA	thaumcarpentry{0.0.1.5-1.7.10} [Thaumcarpentry] (Thaumcarpentry-0.0.1.5-1.7.10.jar) 
	UCHIJA	tc4tweak{1.4.14} [TC4 Tweak] (Thaumcraft4Tweaks-1.4.14.jar) 
	UCHIJA	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHIJA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJA	thaumicbases{1.3.1710.2} [Thaumic Bases] (ThaumicBases-1.3.1710.4.jar) 
	UCHIJA	thaumicdyes{1.10.3} [Thaumic Dyes] (ThaumicDyes-1.7.10-1.10.3-0.jar) 
	UCHIJA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJA	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCHIJA	thaumicinfusion{4.32} [Thaumic Infusion] (ThaumicInfusion-4.32.jar) 
	UCHIJA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear.jar) 
	UCHIJA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJA	wanionlib{1.7.10-1.8} [WanionLib] (WanionLib-1.7.10-1.8.jar) 
	UCHIJA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCHIJA	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCHIJA	worldedit-cui{1.0} [WorldEdit Client User Interface] (WorldEditCUI.jar) 
	UCHIJA	XaeroMinimapFair{21.10.18} [Xaero's Minimap] (Xaeros_Minimap_FP21.10.18_Forge_1.7.10.jar) 
	UCHIJA	XaeroWorldMap{1.14.1.13} [Xaero's World Map] (XaerosWorldMap_1.14.1.13_Forge_1.7.10.jar) 
	UCHIJA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	TC4Tweak signing signature: 004227A857B097EDE4E36FACB9B5491BC9808464, Built by: glease
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Launched Version: 1.7.10
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.79, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 511.79
	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by FalsePattern** [comment]
please submit the `fml-client-latest.log` file.
![image](https://user-images.githubusercontent.com/30945458/163712261-f64cb4f6-f884-4b48-b1a4-fecc2f96ba9c.png)

**Comment by Khikki** [comment]
The trouble is that it is not created for me.
https://gist.github.com/Khikki/7c24b0a5cf527798156d4c6b661f86c8

**Comment by FalsePattern** [comment]
Please check this experimental release, it should fix this problem:
https://maven.falsepattern.com/releases/com/falsepattern/animfix-mc1.7.10/1.3.3-1-g76f631a/animfix-mc1.7.10-1.3.3-1-g76f631a.jar
Once confirmed, i'll release it as 1.3.4
